x-env: &env
  NODE_ENV: production
  HOST: 0.0.0.0
  PORT: ${PORT:-3000}
  LOG_LEVEL: warn

name: react-router-fastify
services:
  app-single-unrestricted:
    image: lfscbe/react-router-fastify-test
    hostname: app-single-unrestricted
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      <<: *env
    restart: unless-stopped
    profiles:
      - single-unrestricted

  app-single-restricted:
    image: lfscbe/react-router-fastify-test
    hostname: app-single-restricted
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      <<: *env
    restart: unless-stopped
    profiles:
      - single-restricted
    deploy:
      resources:
        limits:
          cpus: ${INSTANCE_CPU:-0.5}
          memory: ${INSTANCE_RAM:-0.3G}

  app-multi-instance-1-unrestricted: &app-multi-instance-1-unrestricted
    image: lfscbe/react-router-fastify-test
    hostname: app-multi-instance-1-unrestricted
    environment:
      <<: *env
    restart: unless-stopped
    profiles:
      - multi-restricted

  app-multi-instance-2-unrestricted:
    <<: *app-multi-instance-1-unrestricted
    hostname: app-multi-instance-2-unrestricted

  app-multi-instance-1-restricted: &app-multi-instance-1-restricted
    image: lfscbe/react-router-fastify-test
    hostname: app-multi-instance-1-restricted
    environment:
      <<: *env
    restart: unless-stopped
    profiles:
      - multi-restricted
    deploy:
      resources:
        limits:
          cpus: ${INSTANCE_CPU:-0.5}
          memory: ${INSTANCE_RAM:-0.3G}

  app-multi-instance-2-restricted:
    <<: *app-multi-instance-1-restricted
    hostname: app-multi-instance-2-restricted

  nginx-multi-unrestricted:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx-autogenerated.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - app-multi-instance-1-unrestricted
      - app-multi-instance-2-unrestricted
    restart: unless-stopped
    profiles:
      - multi-unrestricted

  nginx-multi-restricted:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx-autogenerated.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - app-multi-instance-1-restricted
      - app-multi-instance-2-restricted
    restart: unless-stopped
    profiles:
      - multi-restricted
    deploy:
      resources:
        limits:
          cpus: ${NGINX_CPU:-0.15}
          memory: ${NGINX_RAM:-0.2G}
